### ISSUE TITLE
Support for SpringBoot 3 + Reactor Kafka

### ISSUE THREAD

**Issue by patpatpat123** [j-tim/spring-kafka-micrometer#1]
Hello j-tim,

First of all, I wanted to say thanks for this very cool project.
It is very useful, easy to read.

I was wondering, could you help bump this project up to SpringBoot 3, as it has been released.

Most of all, your design is based on Spring Kafka. 
Could you help with Reactor Kafka?
Reactive applications are on the rise, and having an actuator reactor kafka would definitely be a plus.

Thank you

**Comment by j-tim** [comment]
Hi @patpatpat123. I'm sorry for not getting back to you sooner. Thanks for reaching out. Good to know this is useful to you. I created this project a couple of years ago to reproduce an issue with Micrometer and Spring Kafka. You can find a recent version of Spring Kafka and Micrometer in this repository: [https://github.com/j-tim/jfall-2022-spring-kafka-beyond-the-basics](https://github.com/j-tim/jfall-2022-spring-kafka-beyond-the-basics). 

Did you already try to upgrade the project to Spring Boot 3 yourself? And do you have an example application with Reactor Kafka I might be able to help out.

As far as I know, there is no out-of-the-box support for Micrometer in combination with the Reactor Kafka project. This ticket is still open: [Add Micrometer Integration (KafkaClientMetrics)](https://github.com/reactor/reactor-kafka/issues/206)

**Comment by patpatpat123** [comment]
Ouch, indeed, thank you for letting me know. I am hoping this ticket can be merged then.

Thanks a lot and good day!
